import { MediaItem } from '../types/media';

export const MOCK_MEDIA: MediaItem[] = [
  {
    id: '1',
    title: 'Heilsamer Lavendel',
    description: 'Eine Nahaufnahme von frischem Lavendel, bekannt für seine beruhigende Wirkung in der Kräutermedizin.',
    type: 'image',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Lavendel',
    category: 'Kräuter',
    uploadDate: '2026-03-01T10:00:00Z',
  },
  {
    id: '2',
    title: 'Naturgeräusche - Wald',
    description: 'Eine entspannende Videoaufnahme aus dem Herzen eines unberührten Waldes.',
    type: 'video',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Wald+Video',
    duration: '0:45',
    category: 'Natur',
    uploadDate: '2026-02-28T14:30:00Z',
  },
  {
    id: '3',
    title: 'Heilkunde Einführung',
    description: 'Ein Audio-Podcast über die Grundlagen der modernen Pflanzenheilkunde.',
    type: 'audio',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Heilkunde+Audio',
    duration: '3:20',
    category: 'Heilkunde',
    uploadDate: '2026-03-02T09:15:00Z',
  },
  {
    id: '4',
    title: 'Pfefferminze gegen Kopfschmerz',
    description: 'Wie man Pfefferminzöl effektiv zur Linderung von Kopfschmerzen einsetzt.',
    type: 'image',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Pfefferminze',
    category: 'Kopfschmerzen',
    uploadDate: '2026-03-01T16:45:00Z',
  },
  {
    id: '5',
    title: 'Alte Heilkräuter-Bücher',
    description: 'Einblick in historische Dokumente über die Verwendung von Kräutern über die Jahrhunderte.',
    type: 'image',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Alte+Bücher',
    category: 'Heilkunde',
    uploadDate: '2026-02-25T11:20:00Z',
  },
  {
    id: '6',
    title: 'Bachplätschern im Frühling',
    description: 'Beruhigende Audioaufnahme eines plätschernden Bachs zur Entspannung.',
    type: 'audio',
    thumbnailUrl: 'https://via.placeholder.com/300x200?text=Bach+Audio',
    duration: '1:30',
    category: 'Natur',
    uploadDate: '2026-03-02T08:00:00Z',
  },
];
