import { MediaItem, MediaType } from '../types/media';

export const MOCK_MEDIA: MediaItem[] = [
  {
    id: '1',
    title: 'Heilsamer Lavendel',
    description: 'Eine Nahaufnahme von frischem Lavendel, bekannt für seine beruhigende Wirkung in der Kräutermedizin.',
    type: MediaType.IMAGE,
    url: 'https://picsum.photos/id/237/800/600',
    thumbnail: 'https://picsum.photos/id/237/300/200',
    signature: 'Heilkunde > Natur > Kräuter',
    uploadDate: '2026-03-01T10:00:00Z',
  },
  {
    id: '2',
    title: 'Naturgeräusche - Wald',
    description: 'Eine entspannende Videoaufnahme aus dem Herzen eines unberührten Waldes.',
    type: MediaType.VIDEO,
    url: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnail: 'https://via.placeholder.com/300x200?text=Wald+Video',
    duration: '0:45',
    signature: 'Heilkunde > Natur',
    uploadDate: '2026-02-28T14:30:00Z',
  },
  {
    id: '3',
    title: 'Heilkunde Einführung',
    description: 'Ein Audio-Podcast über die Grundlagen der modernen Pflanzenheilkunde.',
    type: MediaType.AUDIO,
    url: 'https://www.w3schools.com/html/horse.mp3',
    thumbnail: 'https://via.placeholder.com/300x200?text=Heilkunde+Audio',
    duration: '3:20',
    signature: 'Heilkunde',
    uploadDate: '2026-03-02T09:15:00Z',
  },
  {
    id: '4',
    title: 'Pfefferminze gegen Kopfschmerz',
    description: 'Wie man Pfefferminzöl effektiv zur Linderung von Kopfschmerzen einsetzt.',
    type: MediaType.IMAGE,
    url: 'https://picsum.photos/id/152/800/600',
    thumbnail: 'https://picsum.photos/id/152/300/200',
    signature: 'Heilkunde > Natur > Kräuter > Kopfschmerzen',
    uploadDate: '2026-03-01T16:45:00Z',
  },
  {
    id: '5',
    title: 'Informatik als Beruf',
    description: 'Einblicke in die moderne Softwareentwicklung und den Karriereweg Informatik.',
    type: MediaType.IMAGE,
    url: 'https://picsum.photos/id/1/800/600',
    thumbnail: 'https://picsum.photos/id/1/300/200',
    signature: 'Gesellschaft > Beruf > Berufswahl > Informatik',
    uploadDate: '2026-02-25T11:20:00Z',
  },
  {
    id: '6',
    title: 'Bachplätschern im Frühling',
    description: 'Beruhigende Audioaufnahme eines plätschernden Bachs zur Entspannung.',
    type: MediaType.AUDIO,
    url: 'https://www.w3schools.com/html/horse.mp3',
    thumbnail: 'https://via.placeholder.com/300x200?text=Bach+Audio',
    duration: '1:30',
    signature: 'Heilkunde > Natur',
    uploadDate: '2026-03-02T08:00:00Z',
  },
];